### PR TITLE
Forward channel data on private channels

### LINKED ISSUE #144: can't subscribe to private channels
I can't subscribe to private channels. I spent about 3 days to find bugs in my side. I successfully subscribe to presence and public channels, but when I try to subscribe private channel I see this error in the debug console `invalid signature: Expected HMAC SHA256 hex digest of`  I don't understand why. I read the pusher docs about private and presence channels and `presence channels is an extension of private channels`. I can't only subscribe to private channels, connect and auth is successfully. Is it bug in the android lib or server side? Thanks. My code
```
PusherAndroidOptions options = new PusherAndroidOptions();
        options.setEncrypted(true);
        HttpAuthorizer authorizer = new HttpAuthorizer(BuildConfig.BASE_ENDPOINT +"api/v1/pusher/auth");
        HashMap<String, String> parameters = new HashMap<>();
        if(user != null) {
            parameters.put("Authorization", user.getAccessToken());
            parameters.put("Client-ID", user.getClientId());
        }
        authorizer.setHeaders(parameters);
        options.setAuthorizer(authorizer);
        pusher = new PusherAndroid("PUSHER_APP_KEY", options);
        PushNotificationRegistration nativePusher = pusher.nativePusher();

        if (pusher.getConnection().getState() == ConnectionState.DISCONNECTED) {
            pusher.connect(new ConnectionEventListener() {
                @Override
                public void onConnectionStateChange(ConnectionStateChange connectionStateChange) {
                    Log.d(TAG, connectionStateChange.getCurrentState().toString());
                    if(connectionStateChange.getCurrentState() == ConnectionState.CONNECTED){
                        PushNotificationRegistrationListener regListener = new PushNotificationRegistrationListener() {
                            @Override
                            public void onSuccessfulRegistration() {
                                Log.d(TAG, "REGISTRATION SUCCESSFUL!!!");
                                Log.d(TAG, "socket id " + pusher.getConnection().getSocketId());
                                PrivateChannel privateChannel = pusher.subscribePrivate("private-messages-125_129");
        privateChannel.bind("new_1v1_message", new PrivateChannelEventListener() {
            @Override
            public void onAuthenticationFailure(String s, Exception e) {
                Log.d(TAG, "onAuthenticationFailure ");
            }

            @Override
            public void onSubscriptionSucceeded(String s) {
                Log.d(TAG, "onSubscriptionSucceeded ");
            }

            @Override
            public void onEvent(String s, String s1, String s2) {
                Log.d(TAG, "onEvent ");
            }
        });
                            }

                            @Override
                            public void onFailedRegistration(int statusCode, String response) {
                                Log.d(TAG,
                                        "A real sad day. Registration failed with code " + statusCode +
                                                " " + response
                                );
                            }
                        };


                        try {
                            nativePusher.registerFCM(context, regListener);
                        } catch (ManifestValidator.InvalidManifestException e) {
                            e.printStackTrace();
                        }
                    }
                }

                @Override
                public void onError(String s, String s1, Exception e) {
                    //e.printStackTrace();
                }
            });
        } else if (pusher.getConnection().getState() == ConnectionState.CONNECTED) {
            pusher.disconnect();
        }
```

### PR DESCRIPTION
**Pull request by WillSewell**
If the auth endpoint returns channel_data, then this should be
forwarded to the auth endpoint even if it is not used by private
channels currently.

This is useful because it allows the same auth endpoint to be
used for private and presence channels.

It also avoids confusing auth signature errors that occur when the
channel_data is not sent (but the auth signature was computed from
it).

Fixes #144.

In order to support the getMe() method on PresenceChannel, we need
to store the channel_data in the PrivateChannelImpl class. This
is decoded in the PresenceChannelImpl class since presence channels
require the channel_data is JSON. It is decoded in toSubscribeMessage()
rather than getMe() to preserve the original semantics (e.g.
exceptions cannot be thrown from getMe().

----

CC @pusher/mobile

### CODE REVIEW

File: src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java [hunk 1]
```diff
@@ -65,35 +64,10 @@ else if (event.equals(MEMBER_REMOVED_EVENT)) {
...
-
-            final String json = GSON.toJson(jsonObject);
-
-            return json;
-        }
-        catch (final Exception e) {
-            throw new AuthorizationFailureException("Unable to parse response from Authorizer: " + authResponse, e);
-        }
+        String msg = super.toSubscribeMessage();
+        storeMyUserId(channelData);
```
Comment (TomKemp) [inline src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java]: Previously, if the channel data was missing (e.g. if someone tried to authorise a presence channel on an auth endpoint only configured to authorise private channels) then it looks like there would have been a null pointer exception thrown in `storeMyUserId` which would have been caught and converted to an `AuthorizationFailureException` above. It looks like now there would just be a null pointer exception. I wonder if it might be better to wrap the call to `storeMyUserId`  in a try catch like before.

File: src/test/java/com/pusher/client/channel/impl/PresenceChannelImplTest.java [hunk 2]
```diff
@@ -60,6 +60,14 @@ public void testReturnsCorrectSubscribeMessageWhenNumericId() {
                 + AUTH_RESPONSE_NUMERIC_ID + "}}", message);
     }
 
+    @Test
+    public void testStoresCorrectUser() {
+        channel.toSubscribeMessage();
```
Comment (TomKemp) [inline src/test/java/com/pusher/client/channel/impl/PresenceChannelImplTest.java]: I don't think it's nice that the user information is added to the presence channel as a side effect of this method call. To me, the name of this method implies there wouldn't be any side effects. But I don't think it needs fixing in this PR as this seems to have been the behaviour before these changes. Might be something to fix in the future though.

File: src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java (hunk 1 above)
Comment (WillSewell) [reply src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java]: Great catch!

Comment (WillSewell) [reply src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java]: Have a look at the latest commit. It should now throw `AuthorizationFailureException`s like before. I also moved the side effect of storing the user id into `toSubscribeMessage`, which I think is cleaner than storing it in a method that is responsible for parsing. I renamed `storeMyUserId` to `extractUserIdFromChannelData` because of this.

`extractUserIdFromChannelData` throws `AuthorizationFailureException` which I think is a bit unclean since it's a fairly generic method that could in theory could have other users. It might be nicer to have a `ParseException` which gets wrapped into a `AuthorizationFailureException` higher up. I don't think this is worth doing now though.

File: src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java [hunk 3]
```diff
@@ -65,35 +66,10 @@ else if (event.equals(MEMBER_REMOVED_EVENT)) {
...
-
-            final String json = GSON.toJson(jsonObject);
-
-            return json;
-        }
-        catch (final Exception e) {
-            throw new AuthorizationFailureException("Unable to parse response from Authorizer: " + authResponse, e);
-        }
+        String msg = super.toSubscribeMessage();
+        myUserID = extractUserIdFromChannelData((String)channelData);
```
Comment (TomKemp) [inline src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java]:
```suggestion
        myUserID = extractUserIdFromChannelData(channelData);
```
I don't think the cast is necessary.

File: src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java [hunk 4]
```diff
@@ -187,9 +163,24 @@ private static PresenceData extractPresenceDataFrom(final String message) {
...
+    private String extractUserIdFromChannelData(final String channelData) {
+        final Map channelDataMap;
+        try {
+            channelDataMap = GSON.fromJson((String)channelData, Map.class);
+        } catch (final JsonSyntaxException e) {
+            throw new AuthorizationFailureException("Invalid response from Authorizer: unable to parse channel_data object: " + channelData, e);
+        }
+        Object maybeUserId;
+        try {
+            maybeUserId = channelDataMap.get("user_id");
```
Comment (TomKemp) [inline src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java]: I don't think `get` throws a null pointer exception if the key doesn't exist, it just returns null, so I don't think the catch block would ever be called. The `if (maybeUserId == null)` check below is sufficient.

In the previous version, `String.valueOf(null)` would have been where the null pointer exception was thrown I think.

Comment (TomKemp) [reply src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java]: Or were you catching `NullPointerException` because `channelDataMap` might be null?

Comment (WillSewell) [reply src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java]: No, I was checking for `NullPointerException` because the `Map` interface "permits" (via documentation) that implementing classes can either return `null` or throw a `NullPointerException` (annoyingly). Even though the concrete type we are using returns `null`, I don't want to rely on this since at this level we are dealing with a `Map`, and shouldn't have to worry about what the concrete implementation is (which unfortunately means checking both cases...).

I don't feel too strongly about this though (I appreciate it could be considered overly cautious). Do you?

Comment (TomKemp) [reply src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java]: Ah I see. I think that sounds OK. Overly cautious is fine with me.

Comment (kn100) [inline src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java]: channelDataMap.containsValue("user_id")? ;)

Comment (WillSewell) [reply src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java]: Thanks @kn100! That is a reasonable suggestion, but I don't think it's worth doing now.
