### PR TITLE
Synchronize everything going on the event queue. Resolves #98 and #54

### LINKED ISSUE #98: IllegalArgumentException
Hi guys,

I had a report of another crash on the version 1.0.2:
`Fatal Exception: java.lang.IllegalArgumentException: Attempted to create an connection state update where both previous and current state are: CONNECTING
       at com.pusher.client.connection.ConnectionStateChange.<init>(ConnectionStateChange.java:21)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:136)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$400(WebSocketConnection.java:27)
       at com.pusher.client.connection.websocket.WebSocketConnection$1.run(WebSocketConnection.java:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)`

### PR DESCRIPTION
**Pull request by jpatel531**
So:

While an event queue (used for connecting, disconnecting, listener events) is shutting down, it still continues as it finishes its final tasks. While it is doing so, if a function that requires an event queue executes, it creates a new one.

This situation can lead to two event queues running at the same time. Issues #98 and #54 were, I believe, caused by an extremely subtle race condition where certain factors (e.g. custom reconnection logic, multiple instances of Pusher etc.) would cause multiple connection operations to be called at the same time. If a socket has been shut down - leading to an event queue being asked to shut down - and then there are multiple calls to connect executed on more than one event queue, you could get a race condition.

This led to inconsistencies regarding the connection `state`. If two threads see that that the `state` is `DISCONNECTED`, one gets there first and updates the state to `CONNECTING` and then the second thread tries to update the state to `CONNECTING`, we will get `java.lang.IllegalArgumentException: Attempted to create an connection state update where both previous and current state are: CONNECTING`.

In light of this, all Runnables put on the event queue are now wrapped in a synchronized block. The factory forever holds this lock and in the event there are two concurrent event queues, it will synchronize the Runnables.

cc @mdpye

### CODE REVIEW

File: src/test/java/com/pusher/client/channel/impl/ChannelImplTest.java [hunk 1]
```diff
@@ -27,7 +29,14 @@
 
     @Before
     public void setUp() {
-        when(factory.getEventQueue()).thenReturn(new InstantExecutor());
+        doAnswer(new Answer() {
+            @Override
+            public Object answer(InvocationOnMock invocation) throws Throwable {
+                final Runnable r = (Runnable) invocation.getArguments()[0];
+                new InstantExecutor().execute(r);
```
Comment (mdpye) [inline src/test/java/com/pusher/client/channel/impl/ChannelImplTest.java]: This `InstantExecutor` class is probably redundant now.

`((Runnable)invocation.getArguments()[0]).run();` would do the trick.

To stick to proper OO patterns, we should really create a `GloballySynchronizedExecutor` which takes the lock object as a constructor arg, then we could still return a dummy type here.
Not going to insist on it though.
